# -*- coding: utf-8 -*-
"""raytheon_ugv_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKqn_z1nqyIPbQRp3a9TJgLyDWJFEfl9
"""

!pip install tensorflow==2.19.1
!pip install akida==2.19.1
!pip install cnn2snn==2.19.1
!pip install akida-models==1.13.1

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive/Buckets and Traffic Cones.voc (3)"

import tensorflow as tf
import tf_keras

DATASET_DIR = "/content/drive/MyDrive/Buckets and Traffic Cones.voc (3)"
TRAIN_RECORD = DATASET_DIR + "/train.record"
VAL_RECORD = DATASET_DIR + "/val.record"

print(TRAIN_RECORD)
print(VAL_RECORD)

GRID_SIZE = 7
IMG_SIZE = 224
NUM_CLASSES = 4

def parse_example(example_proto):
    feature_description = {
        "image/encoded": tf.io.FixedLenFeature([], tf.string),
        "image/object/bbox/xmin": tf.io.VarLenFeature(tf.float32),
        "image/object/bbox/xmax": tf.io.VarLenFeature(tf.float32),
        "image/object/bbox/ymin": tf.io.VarLenFeature(tf.float32),
        "image/object/bbox/ymax": tf.io.VarLenFeature(tf.float32),
        "image/object/class/label": tf.io.VarLenFeature(tf.int64),
    }

    parsed = tf.io.parse_single_example(example_proto, feature_description)

    image = tf.image.decode_jpeg(parsed["image/encoded"], channels=3)
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE)) / 255.0

    xmin = tf.sparse.to_dense(parsed["image/object/bbox/xmin"])
    xmax = tf.sparse.to_dense(parsed["image/object/bbox/xmax"])
    ymin = tf.sparse.to_dense(parsed["image/object/bbox/ymin"])
    ymax = tf.sparse.to_dense(parsed["image/object/bbox/ymax"])
    labels = tf.sparse.to_dense(parsed["image/object/class/label"])

    target = tf.zeros((GRID_SIZE, GRID_SIZE, 5 + NUM_CLASSES), dtype=tf.float32)

    def loop_body(i, target):
        x_center = (xmin[i] + xmax[i]) / 2.0
        y_center = (ymin[i] + ymax[i]) / 2.0
        w = xmax[i] - xmin[i]
        h = ymax[i] - ymin[i]

        grid_x = tf.cast(x_center * GRID_SIZE, tf.int32)
        grid_y = tf.cast(y_center * GRID_SIZE, tf.int32)

        grid_x = tf.clip_by_value(grid_x, 0, GRID_SIZE - 1)
        grid_y = tf.clip_by_value(grid_y, 0, GRID_SIZE - 1)

        class_vec = tf.one_hot(labels[i], NUM_CLASSES)

        update = tf.concat([
            [x_center, y_center, w, h, 1.0],
            class_vec
        ], axis=0)

        target = tf.tensor_scatter_nd_update(
            target,
            indices=[[grid_y, grid_x]],
            updates=[update]
        )

        return i + 1, target

    i = tf.constant(0)
    n = tf.shape(labels)[0]

    _, target = tf.while_loop(
        lambda i, target: i < n,
        loop_body,
        [i, target]
    )

    return image, target

BATCH_SIZE = 8

train_ds = tf.data.TFRecordDataset(TRAIN_RECORD)
train_ds = train_ds.map(parse_example)
train_ds = train_ds.shuffle(300)
train_ds = train_ds.batch(BATCH_SIZE)
train_ds = train_ds.prefetch(tf.data.AUTOTUNE)

val_ds = tf.data.TFRecordDataset(VAL_RECORD)
val_ds = val_ds.map(parse_example)
val_ds = val_ds.batch(BATCH_SIZE)
val_ds = val_ds.prefetch(tf.data.AUTOTUNE)

print("Datasets ready")

from tf_keras import layers, Model, Input

PRED_SIZE = 5 + NUM_CLASSES

inputs = Input(shape=(IMG_SIZE, IMG_SIZE, 3))

x = layers.Conv2D(32, 3, strides=2, padding="same", activation="relu")(inputs)
x = layers.Conv2D(64, 3, strides=2, padding="same", activation="relu")(x)
x = layers.Conv2D(128, 3, strides=2, padding="same", activation="relu")(x)
x = layers.Conv2D(128, 3, strides=2, padding="same", activation="relu")(x)
x = layers.Conv2D(256, 3, strides=2, padding="same", activation="relu")(x)

x = layers.Resizing(GRID_SIZE, GRID_SIZE)(x)
x = layers.Conv2D(128, 3, padding="same", activation="relu")(x)

outputs = layers.Conv2D(PRED_SIZE, 1, padding="same", activation=None)(x)

det_model = Model(inputs=inputs, outputs=outputs)
det_model.summary()

def detection_loss(y_true, y_pred):
    true_box = y_true[..., 0:4]
    true_obj = y_true[..., 4:5]
    true_cls = y_true[..., 5:]

    pred_box = tf.sigmoid(y_pred[..., 0:4])
    pred_obj = tf.sigmoid(y_pred[..., 4:5])
    pred_cls = tf.nn.softmax(y_pred[..., 5:])

    box_loss = tf.reduce_sum(true_obj * tf.square(true_box - pred_box))

    obj_loss_pos = tf.reduce_sum(true_obj * tf.square(1.0 - pred_obj))
    obj_loss_neg = tf.reduce_sum((1.0 - true_obj) * tf.square(pred_obj))

    ce = tf_keras.losses.categorical_crossentropy(true_cls, pred_cls)
    ce = tf.expand_dims(ce, axis=-1)
    cls_loss = tf.reduce_sum(true_obj * ce)

    return (10.0 * box_loss) + (100.0 * obj_loss_pos) + (0.05 * obj_loss_neg) + cls_loss

det_model.compile(
    optimizer=tf_keras.optimizers.Adam(learning_rate=0.0003),
    loss=detection_loss
)

history = det_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=50
)

def iou(box1, box2):
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    inter = max(0, x2 - x1) * max(0, y2 - y1)

    area1 = (box1[2]-box1[0]) * (box1[3]-box1[1])
    area2 = (box2[2]-box2[0]) * (box2[3]-box2[1])

    union = area1 + area2 - inter
    return inter / (union + 1e-6)

def decode_predictions(pred, conf_thresh=0.3):
    boxes = []

    for y in range(GRID_SIZE):
        for x in range(GRID_SIZE):
            cell = pred[y, x]

            bx, by, bw, bh = cell[0:4]
            obj = 1 / (1 + np.exp(-np.clip(cell[4], -10, 10)))
            cls = cell[5:]
            cls = np.exp(cls) / np.sum(np.exp(cls))

            score = obj * np.max(cls)
            class_id = np.argmax(cls)

            if score > conf_thresh:
                cx = (x + bx) / GRID_SIZE
                cy = (y + by) / GRID_SIZE

                xmin = cx - bw / 2
                ymin = cy - bh / 2
                xmax = cx + bw / 2
                ymax = cy + bh / 2

                boxes.append([xmin, ymin, xmax, ymax, score, class_id])

    boxes = sorted(boxes, key=lambda x: x[4], reverse=True)

    filtered = []
    for box in boxes:
        keep = True
        for f in filtered:
            if iou(box, f) > 0.4:
                keep = False
                break
        if keep:
            filtered.append(box)

    return filtered

import matplotlib.pyplot as plt

CLASS_NAMES = ["bucket", "cone", "box", "ramp"]

def show_prediction(image, pred):
    boxes = decode_predictions(pred)

    h, w, _ = image.shape
    plt.imshow(image)

    for box in boxes:
        xmin, ymin, xmax, ymax, score, cls = box

        xmin *= w
        xmax *= w
        ymin *= h
        ymax *= h

        plt.gca().add_patch(
            plt.Rectangle(
                (xmin, ymin),
                xmax - xmin,
                ymax - ymin,
                fill=False,
                color="red",
                linewidth=2
            )
        )

        plt.text(xmin, ymin, f"{CLASS_NAMES[int(cls)]}:{score:.2f}", color="red")

    plt.show()

for images, targets in train_ds.take(1):
    print("Target shape:", targets.shape)
    print("Max target objectness:", tf.reduce_max(targets[..., 4]).numpy())
    print("Number of object cells:", tf.reduce_sum(targets[..., 4]).numpy())

import numpy as np

import numpy as np

for images, targets in val_ds.take(1):
    preds = det_model.predict(images)

    img = images[0].numpy()
    pred = preds[0]

    obj_scores = 1 / (1 + np.exp(-pred[..., 4]))
    print("Max objectness:", np.max(obj_scores))
    print("Min objectness:", np.min(obj_scores))
    print("Mean objectness:", np.mean(obj_scores))

    show_prediction(img, pred)

from quantizeml.models import quantize
from cnn2snn import convert

quantized_model = quantize(det_model)

akida_model = convert(quantized_model)

akida_model.save("detector_improved.fbz")

print("Saved detector_improved.fbz")

from google.colab import files
files.download("detector_improved.fbz")